### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by wbuschha** [rhockenbury/homebridge-ecowitt-weather-sensors#37]
I am running this plugin in Homebridge on a Raspberry Pi 4B, and it is not logging the activities. Is that an issue on my end, or an expected behavior?

**Comment by rhockenbury** [comment]
Hi @wbuschha. Thanks for reaching out.  The data report is logged at a debug level, which isn't shown in the Homebridge logs by default. I have [written instructions here](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/wiki/Submitting-Data-Report) for getting the plugin to log the data reports, which boils down to enabling debug mode and restarting Homebridge.  Let me know if that helps, or if you meant something else when you said "activities." 

Let me know if you have thoughts about whether the data reports should be logged by default.  I didn't want the plugin to be too noisy with a log message on every data report so opted not to, but I could potentially log it by default, and add a config option to disable the data report log message for those that find it too noisy.

**Comment by wbuschha** [comment]
Hi Ryler,Thank you for your super fast response. I really appreciate it, and the log works now with the debug mode enabled.On Oct 10, 2024, at 21:47, Ryler Hockenbury ***@***.***> wrote:﻿
Hi @wbuschha. Thanks for reaching out.  The data report is logged at a debug level, which isn't shown in the Homebridge logs by default. I have written instructions here for getting the plugin to log the data reports, which boils down to enabling debug mode and restarting Homebridge.  Let me know if that helps, or if you meant something else when you said "activities."
Let me know if you have thoughts about whether the data reports should be logged by default.  I didn't want the plugin to be too noisy with a log message on every data report so opted not to, but I could potentially log it by default, and add a config option to disable the data report log message for those that find it too noisy.
