### ISSUE TITLE
Wind, rain, and UV display as motion sensors

### ISSUE THREAD

**Issue by lcetor** [rhockenbury/homebridge-ecowitt-weather-sensors#40]
***

name: Bug Report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

***

**Describe The Bug:**

All wind, rain, and UV data show up as motion sensors rather than actual values.
Also (possibly related?), when restarting the plugin I get this error:
[Ecowitt] Base station was not detected from the data report. Please file a bug report at https://bit.ly/3yklrWZ

**To Reproduce:**

Restart plugin to receive error message.

**Expected behavior:**

I would expect to see these sensors report the actual value - mph, in, etc rather than an on/off motion.
Also expect no base station error on restart.

**Logs:**

```
[11/3/2024, 12:26:53 PM] [Ecowitt] Restarting child bridge...
[11/3/2024, 12:26:53 PM] Got SIGTERM, shutting down child bridge process...
[11/3/2024, 12:26:58 PM] [Ecowitt] Child bridge process ended
[11/3/2024, 12:26:58 PM] [Ecowitt] Process Ended. Code: 143, Signal: null
[11/3/2024, 12:27:05 PM] [Ecowitt] Restarting Process...
[11/3/2024, 12:27:06 PM] [Ecowitt] Launched child bridge with PID 1718396
[11/3/2024, 12:27:06 PM] Registering platform 'homebridge-ecowitt-weather-sensors.Ecowitt'
[11/3/2024, 12:27:06 PM] [Ecowitt] Loaded homebridge-ecowitt-weather-sensors v2.5.1 child bridge successfully
[11/3/2024, 12:27:06 PM] Loaded 5 cached accessories from cachedAccessories.
[11/3/2024, 12:27:06 PM] [Ecowitt] Listening for data reports on 8001 /path/report
[11/3/2024, 12:27:06 PM] Homebridge v1.8.5 (HAP v0.12.3) (Ecowitt) is running on port 55861.
[11/3/2024, 12:27:06 PM] 
[11/3/2024, 12:27:15 PM] [Ecowitt] Registering accessories from data report
[11/3/2024, 12:27:15 PM] [Ecowitt] Base station was not detected from the data report. Please file a bug report at https://bit.ly/3yklrWZ
[11/3/2024, 12:27:15 PM] [Ecowitt] Restoring existing accessory from cache - type: WS90, uuid: aacf85b9
[11/3/2024, 12:27:15 PM] [Ecowitt] Note that accessory WS90 does not currently use and/or display the following data: ws90cap_volt,ws90_ver
[11/3/2024, 12:27:15 PM] [Ecowitt] Restoring existing accessory from cache - type: WH51, uuid: 5bc44742
[11/3/2024, 12:27:15 PM] [Ecowitt] Note that accessory WH51 does not currently use and/or display the following data: soilad1
[11/3/2024, 12:27:15 PM] [Ecowitt] Restoring existing accessory from cache - type: WH51, uuid: 012941b9
[11/3/2024, 12:27:15 PM] [Ecowitt] Note that accessory WH51 does not currently use and/or display the following data: soilad2
[11/3/2024, 12:27:15 PM] [Ecowitt] Restoring existing accessory from cache - type: WN31, uuid: 02d68843
[11/3/2024, 12:27:15 PM] [Ecowitt] Restoring existing accessory from cache - type: WN30, uuid: abfc9ae3
```

**Data Report:**

```
{
  "PASSKEY": "",
  "stationtype": "WN1980B_V1.3.2",
  "runtime": "1543472",
  "heap": "67788",
  "dateutc": "2024-11-03 17:09:27",
  "tempinf": "94.64",
  "humidityin": "22",
  "baromrelin": "29.870",
  "baromabsin": "28.369",
  "tempf": "61.16",
  "humidity": "45",
  "winddir": "40",
  "windspeedmph": "5.37",
  "windgustmph": "8.28",
  "maxdailygust": "17.00",
  "solarradiation": "308.76",
  "uv": "2",
  "rrain_piezo": "0.000",
  "erain_piezo": "0.000",
  "hrain_piezo": "0.000",
  "drain_piezo": "0.000",
  "wrain_piezo": "0.000",
  "mrain_piezo": "0.004",
  "yrain_piezo": "12.465",
  "ws90cap_volt": "4.4",
  "ws90_ver": "138",
  "temp1f": "56.48",
  "humidity1": "57",
  "temp2f": "85.28",
  "soilmoisture1": "60",
  "soilad1": "244",
  "soilmoisture2": "52",
  "soilad2": "217",
  "console_batt": "2.91",
  "batt1": "0",
  "batt2": "0",
  "soilbatt1": "1.4",
  "soilbatt2": "1.5",
  "wh90batt": "3.06",
  "freq": "915M",
  "model": "WN1980B",
  "interval": "10"
}
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "",
        "port": 51546,
        "pin": "",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config",
            "tempUnits": "f"
        },
        {
            "name": "Ecowitt",
            "baseStation": {
                "mac": "",
                "port": 8001,
                "path": "/path/report"
            },
            "nameOverrides": [
                {
                    "key": "WS90:Temperature",
                    "value": "Current Temp"
                },
                {
                    "key": "WN31CH1:Temperature",
                    "value": "Storage Temp"
                },
                {
                    "key": "WN31CH1:Humidity",
                    "value": "Storage Humidity"
                },
                {
                    "key": "WN30CH2",
                    "value": "Compost Temp"
                }
            ],
            "additional": {
                "staticNames": "true",
                "validateMac": "true",
                "luxFactor": 126.7,
                "acceptAnyPath": "false",
                "validateTimestamp": "true",
                "removeStaleDevices": "true"
            },
            "thresholds": {
                "windSpeed": 16,
                "windGustSpeed": 20,
                "rainRate": 0.1
            },
            "hidden": {
                "windMaxDailySpeed": true,
                "rainWeeklyTotal": true,
                "rainMonthlyTotal": true,
                "rainYearlyTotal": true,
                "waterLeak": true,
                "leafWetness": true,
                "airQualityPM25": true,
                "airQualityPM25Avg": true,
                "airQualityPM10": true,
                "airQualityPM10Avg": true,
                "carbonDioxide": true,
                "carbonDioxideAvg": true,
                "lightningEvents": true,
                "lightningDistance": true,
                "lightningTime": true
            },
            "units": {
                "wind": "mph",
                "rain": "in",
                "distance": "mi",
                "temperature": "fh"
            },
            "_bridge": {
                "username": "",
                "port": 55861
            },
            "platform": "Ecowitt"
        }
    ]
}
```

**Screenshots:**
![homebridge](https://github.com/user-attachments/assets/7623acac-948a-423a-8467-c039bbe2036e)

**Environment:**

* **Plugin Version**:  2.5.1
* **Homebridge Version**:   1.8.5
* **Node.js Version**:  20.18.0
* **NPM Version**:  10.8.2
* **Operating System**:  Ubuntu 22.04.4

**Comment by rhockenbury** [comment]
Hi @lcetor.  Thanks for reaching out.  It looks like you are describing two separate things - 

(1) Homekit does not have native services to support all the data available from Ecowitt devices.   Whenever possible, a weather data property is mapped to it's equivalent service (humidity -> humidity), but in some cases, there is no equivalent service for a weather data property.  For example, there is no Homekit "Rain" sensor which makes it a challenge to display that weather data property in a useful way that works well with Homekit.  In these cases, a motion sensor is used which triggers based on the user supplied thresholds.

Please also note that third-party Homekit apps are able to show custom characteristics on a service (native Homekit app does not).   I've implemented custom characteristics to show the weather data on the motion sensors.  So for instance in Controller for Homekit, it shows - 

![IMG_0454](https://github.com/user-attachments/assets/266abcd4-e729-418b-9b87-6756ae42cc50)

I would definitely recommend using a third-party Homekit app to get the most out of this plugin.  Let me know if that helps explain the situation. 

(2) The log message `Base station was not detected from the data report ...` indicates that support for WN1980B has not been implemented.  The plugin will still work fine without support for your base station - it just won't show an accessory for the base station with the indoor humidity and indoor temperature values.   I have expanded support for Ecowitt base stations that I'm planning to roll into the work I'm doing to support Ambient Weather devices, and that version would introduce support for WN1980.  Let me know if that sounds ok.

**Comment by rhockenbury** [comment]
👍 Yeah, I agree, it's a major pain not to be able to do automations with that data in homekit.  I believe if you use Home Assistant, you can use the custom characteristics in automations.  I personally use node-red w/ [the homebridge plugin](https://flows.nodered.org/node/node-red-contrib-homebridge-automation) which makes all the service characteristics available for automations.

**Comment by rhockenbury** [comment]
Hi @lcetor.  Please try out v2.7.0-beta for support for the WN1980 gateway, and let me know if you hit any issues.

And if you feel you are getting value from this plugin, please consider giving this repo a star. Thanks!
