### ISSUE TITLE
WH51 soil moisture accessory names not reflected in HomeKit ?

### ISSUE THREAD

**Issue by NiftyMac** [rhockenbury/homebridge-ecowitt-weather-sensors#47]
Hoping you can help me here with working out why the accessory names that are applied in the WSView app do not flow through to Homekit ?  The names just stay as "Soil Moisture", which of course makes it difficult to work with in Homekit when trying to set up automations etc.
I did look at Names Override in the plugin but could not figure out how to do this?

![IMG_0110](https://github.com/user-attachments/assets/060feb80-b8b5-44ca-b29a-b7344c20204f)
![IMG_0109](https://github.com/user-attachments/assets/adc37c76-a234-48b2-b29c-3013baddbd72)
thank you.

**Comment by rhockenbury** [comment]
Hi @NiftyMac.  The plugin does not sync service names with the names in the WSView App.  As you mentioned, to provide custom names for those services in Homekit, the Name Overrides feature needs to be used.

Go to the "Name Override" section in the plugin config, and try this - 

| Sensor Id  |  Name Override |
| -------- | ------- |
| WH51CH1 | Monstera Pot |
| WH51CH2 | Vege Patch |
| WH51CH3 | Deck Garden Bed |
| WH51CH4 | Peace Lilly Pot |

After making that change to the plugin config, Homebridge will need to be restarted.

**Comment by NiftyMac** [comment]
Great!  thank you so much, just was unsure of the format of the sensor ID. All working now.
